import { Building } from "@/types";

// --- 2. NHÓM TRANG TRÍ & PHỤ TRỢ (SECONDARY) ---
export const SECONDARY_BUILDINGS: Building[] = [
  {
    id: "avacado_tree",
    name: "Cây bơ cổ thụ",
    description:
      "Cây bơ thần kỳ tỏa bóng mát toàn khu vực, trái của nó cung cấp năng lượng vĩnh cửu cho cư dân.",
    worldX: 4,
    worldY: -1,
    width: 3,
    height: 3,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/buildings/avacado_tree.png",
    interactive: true,
  },
  {
    id: "sale1",
    name: "Mặt tiền A1",
    description:
      "Cây bơ thần kỳ tỏa bóng mát toàn khu vực, trái của nó cung cấp năng lượng vĩnh cửu cho cư dân.",
    worldX: -2,
    worldY: -7,
    width: 4,
    height: 3,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/decorate/sale.png",
    interactive: true,
  },
  {
    id: "sale2",
    name: "Mặt tiền A2",
    description:
      "Cây bơ thần kỳ tỏa bóng mát toàn khu vực, trái của nó cung cấp năng lượng vĩnh cửu cho cư dân.",
    worldX: 7,
    worldY: -7,
    width: 4,
    height: 3,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/decorate/sale.png",
    interactive: true,
  },
  {
    id: "sale3",
    name: "Mặt tiền A3",
    description:
      "Cây bơ thần kỳ tỏa bóng mát toàn khu vực, trái của nó cung cấp năng lượng vĩnh cửu cho cư dân.",
    worldX: -11,
    worldY: -7,
    width: 4,
    height: 3,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/decorate/sale.png",
    interactive: true,
  },
];

// --- 3. NHÓM CHIẾU SÁNG (TORCHES) ---
export const TORCH_BUILDINGS: Building[] = [
  {
    id: "torch1",
    name: "Đuốc Vĩnh Cửu",
    description:
      "Ngọn lửa không bao giờ tắt, xua tan bóng tối và những sinh vật hắc ám quanh bờ tường.",
    worldX: -6,
    worldY: 5,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
  {
    id: "torch2",
    name: "Đuốc Vĩnh Cửu",
    description: "Xua tan bóng tối đêm đen.",
    worldX: 5,
    worldY: 5,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
  {
    id: "torch3",
    name: "Đuốc Vĩnh Cửu",
    description: "Xua tan bóng tối đêm đen.",
    worldX: 3,
    worldY: 1,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
  {
    id: "torch4",
    name: "Đuốc Vĩnh Cửu",
    description: "Xua tan bóng tối đêm đen.",
    worldX: -4,
    worldY: 1,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
];

// --- 4. NHÓM PHÒNG THỦ (DEFENSE / WALLS) ---
export const DEFENSE_BUILDINGS: Building[] = [
  {
    id: "gate",
    name: "Cổng Chính",
    description:
      "Cánh cổng kiên cố ngăn cách nội đô với thế giới bên ngoài đầy hiểm nguy.",
    worldX: -4,
    worldY: 7,
    width: 8,
    height: 2,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/defenese/gate.png",
    interactive: true,
  },
  {
    id: "gate2",
    name: "Cổng Hậu",
    description: "Lối thoát hiểm bí mật dẫn ra khu rừng phía sau vương quốc.",
    worldX: -4,
    worldY: -11,
    width: 8,
    height: 2,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/defenese/gate.png",
    interactive: true,
  },
  {
    id: "wall1",
    name: "Tường thành Nam",
    description: "Phòng tuyến kiên cố.",
    worldX: 4,
    worldY: 7,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall.png",
    interactive: true,
  },
  {
    id: "wall2",
    name: "Tường thành Nam",
    description: "Phòng tuyến kiên cố.",
    worldX: -14,
    worldY: 7,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall.png",
    interactive: true,
  },
  {
    id: "wall3",
    name: "Tường thành Tây",
    description: "Phòng tuyến kiên cố.",
    worldX: -16,
    worldY: -1,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_left.png",
    interactive: true,
  },
  {
    id: "wall4",
    name: "Tường thành Tây",
    description: "Phòng tuyến kiên cố.",
    worldX: -16,
    worldY: -11,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_left.png",
    interactive: true,
  },
  {
    id: "wall5",
    name: "Tường thành Đông",
    description: "Phòng tuyến kiên cố.",
    worldX: 14,
    worldY: -1,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_right.png",
    interactive: true,
  },
  {
    id: "wall6",
    name: "Tường thành Đông",
    description: "Phòng tuyến kiên cố.",
    worldX: 14,
    worldY: -11,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_right.png",
    interactive: true,
  },
  {
    id: "wall8",
    name: "Tường thành Bắc",
    description: "Phòng tuyến kiên cố.",
    worldX: -14,
    worldY: -11,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_top.png",
    interactive: true,
  },
  {
    id: "wall9",
    name: "Tường thành Bắc",
    description: "Phòng tuyến kiên cố.",
    worldX: 4,
    worldY: -11,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_top.png",
    interactive: true,
  },
];