import { Building } from "@/stores/types";

// --- 2. NHÓM TRANG TRÍ & PHỤ TRỢ (SECONDARY) ---
export const SECONDARY_BUILDINGS: Building[] = [
  {
    id: "avacado_tree",
    name: "Cây bơ cổ thụ",
    description:
      "Cây bơ thần kỳ tỏa bóng mát toàn khu vực, trái của nó cung cấp năng lượng vĩnh cửu cho thần dân.",
    worldX: 4,
    worldY: -1,
    width: 3,
    height: 3,
    type: "decoration",
    animationType: "shake_on_click",
    imageSrc: "/assets/buildings/avacado_tree.png",
    interactive: true,
  },
  {
    id: "sale1",
    name: "Mặt tiền A1",
    description:
      "Cây bơ thần kỳ tỏa bóng mát toàn khu vực, trái của nó cung cấp năng lượng vĩnh cửu cho thần dân.",
    worldX: -1,
    worldY: -6,
    width: 4,
    height: 3,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/decorate/sale.png",
    interactive: true,
  },

  {
    id: "pool",
    name: "Bể bơi",
    description:
      "Nơi thư giãn và tái tạo năng lượng cho các thần dân vương quốc.",
    worldX: 4,
    worldY: -9,
    width: 6,
    height: 6,
    zIndex: 0,

    type: "secondary",
    imageSrc: "/assets/decorate/pool.png",
    interactive: true,
  },
  {
    id: "tuna",
    name: "Genji",
    description:
      "Sinh vật huyền thoại sống trong bể bơi, chỉ xuất hiện khi có sự kiện đặc biệt. Người ta đồn rằng tuna",
    worldX: 6, // nằm trong pool (giữa pool theo X)
    worldY: -7, // nằm trong pool (giữa pool theo Y)
    width: 1,
    height: 1,
    interactive: true,
    zIndex: 1, // cao hơn pool → được pick khi chồng
    type: "main", // hoặc bất kỳ type nào phù hợp
    imageSrc: "/assets/decorate/tuna.png",
    // hidden: true -- KHÔNG đặt ở đây, handled bởi tunaVisible trong store
  },
  {
    id: "trophy",
    name: "Cúp vô địch",
    description:
      "Nơi thư giãn và tái tạo năng lượng cho các thần dân vương quốc.",
    worldX: 11,
    worldY: -7,
    width: 3,
    height: 3,
    zIndex: 0,

    type: "secondary",
    imageSrc: "/assets/decorate/trophy.png",
    interactive: true,
  },
  {
    id: "t1",
    name: "GG",
    description:
      "Sinh vật huyền thoại sống trong bể bơi, chỉ xuất hiện khi có sự kiện đặc biệt. Người ta đồn rằng tuna",
    worldX: 10, // nằm trong pool (giữa pool theo X)
    worldY: -9, // nằm trong pool (giữa pool theo Y)
    width: 3,
    height: 3,
    interactive: true,
    zIndex: 1, // cao hơn pool → được pick khi chồng
    type: "secondary", // hoặc bất kỳ type nào phù hợp
    imageSrc: "/assets/decorate/t1.png",
  },
];

// --- 3. NHÓM CHIẾU SÁNG (TORCHES) ---
export const TORCH_BUILDINGS: Building[] = [
  {
    id: "torch1",
    name: "Đuốc Vĩnh Cửu",
    description:
      "Ngọn lửa không bao giờ tắt, xua tan bóng tối và những sinh vật hắc ám quanh bờ tường.",
    worldX: -6,
    worldY: 5,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
  {
    id: "torch2",
    name: "Đuốc Vĩnh Cửu",
    description: "Xua tan bóng tối đêm đen.",
    worldX: 5,
    worldY: 5,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
  {
    id: "torch3",
    name: "Đuốc Vĩnh Cửu",
    description: "Xua tan bóng tối đêm đen.",
    worldX: 3,
    worldY: 1,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
  {
    id: "torch4",
    name: "Đuốc Vĩnh Cửu",
    description: "Xua tan bóng tối đêm đen.",
    worldX: -4,
    worldY: 1,
    width: 1,
    height: 1,
    type: "torch",
    imageSrc: "/assets/decorate/duoc.png",
    interactive: true,
  },
];

// --- 4. NHÓM PHÒNG THỦ (DEFENSE / WALLS) ---
export const DEFENSE_BUILDINGS: Building[] = [
  {
    id: "gate",
    name: "Cổng Chính",
    description:
      "Cánh cổng kiên cố ngăn cách nội đô với thế giới bên ngoài đầy hiểm nguy.",
    worldX: -4,
    worldY: 7,
    width: 8,
    height: 2,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/defenese/gate.png",
    interactive: true,
  },
  {
    id: "gate2",
    name: "Cổng Hậu",
    description: "Lối thoát hiểm bí mật dẫn ra khu rừng phía sau vương quốc.",
    worldX: -4,
    worldY: -11,
    width: 8,
    height: 2,
    type: "secondary",
    animationType: "shake_on_click",
    imageSrc: "/assets/defenese/gate.png",
    interactive: true,
  },
  {
    id: "wall1",
    name: "Tường thành Nam",
    description: "Phòng tuyến kiên cố.",
    worldX: 4,
    worldY: 7,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall.png",
    interactive: true,
  },
  {
    id: "wall2",
    name: "Tường thành Nam",
    description: "Phòng tuyến kiên cố.",
    worldX: -14,
    worldY: 7,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall.png",
    interactive: true,
  },
  {
    id: "wall3",
    name: "Tường thành Tây",
    description: "Phòng tuyến kiên cố.",
    worldX: -16,
    worldY: -1,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_left.png",
    interactive: true,
  },
  {
    id: "wall4",
    name: "Tường thành Tây",
    description: "Phòng tuyến kiên cố.",
    worldX: -16,
    worldY: -11,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_left.png",
    interactive: true,
  },
  {
    id: "wall5",
    name: "Tường thành Đông",
    description: "Phòng tuyến kiên cố.",
    worldX: 14,
    worldY: -1,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_right.png",
    interactive: true,
  },
  {
    id: "wall6",
    name: "Tường thành Đông",
    description: "Phòng tuyến kiên cố.",
    worldX: 14,
    worldY: -11,
    width: 2,
    height: 10,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_right.png",
    interactive: true,
  },
  {
    id: "wall8",
    name: "Tường thành Bắc",
    description: "Phòng tuyến kiên cố.",
    worldX: -14,
    worldY: -11,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_top.png",
    interactive: true,
  },
  {
    id: "wall9",
    name: "Tường thành Bắc",
    description: "Phòng tuyến kiên cố.",
    worldX: 4,
    worldY: -11,
    width: 10,
    height: 2,
    type: "secondary",
    imageSrc: "/assets/defenese/wall_top.png",
    interactive: true,
  },
];
